apiVersion: skaffold/v2beta26
kind: Config
deploy:
  helm:
    releases:
      - name: streaming-grpc-releases
        chartPath: "./deployments/k8s"
        createNamespace: true
        namespace: streaming-grpc
        artifactOverrides:
          image: streaming-grpc
build:
  local:
    push: false
  artifacts:
    - image: streaming-grpc
      context: .
