apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
spec:
  selector:
    matchLabels:
      app: streaming-grpc-exercise
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      containers:
      - name: streaming-grpc-exercise
        image: streaming-grpc-exercise
        command:
          - "sh"
          - "-c"
          - "/app/streaming-grpc-exercise"
        envFrom:
          - configMapRef:
              name: config
