apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "streaming-grpc.fullname" . }}
  labels:
    {{- include "streaming-grpc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "streaming-grpc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        proxy.istio.io/config: |
          holdApplicationUntilProxyStarts: true
          concurrency: 0
        sidecar.istio.io/logLevel: "debug"
        sidecar.istio.io/userVolume: '[{"name":"descriptor","configMap":{"name":"proto-descriptor","items":[{"key":"proto.pb","path":"proto.pb"}]}}]'
        sidecar.istio.io/userVolumeMount: '[{"name":"descriptor","mountPath":"/etc/envoy"}]'
      labels:
        {{- include "streaming-grpc.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
