apiVersion: v1
kind: Service
metadata:
  name: {{ include "streaming-grpc.fullname" . }}
  labels:
    {{- include "streaming-grpc.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.app.environments.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "streaming-grpc.selectorLabels" . | nindent 4 }}
